### PR TITLE
remove hardlink to bootable/recovery path

### PR DESCRIPTION
**Pull request by championswimmer**
if using multi-recovery system, this recovery might not necessarily be in bootable/recovery folder

it should be rather in bootable/recovery-philz/ folder.

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
thanks

**Comment by championswimmer** [comment]
Also, couldn't find any way to contact you via pm/mail/xda,
So asking right here,
I am am on the official AOKP team and I maintain all the 2012-13 Xperias
So, is it okay to include your recovery as the default one inside the bootimages of official AOKP nightlies.
(AOKP does not distribute a recovery in the zip usually, but in the Xperia devices, the recovery is part of the main ramdisk so it is bundled... and we have been using CWM till now)
Thanks

You can reply here or ping me on championswimmer@gmail.com

**Comment by PhilZ-cwm6** [comment]
sure

You can freely do. Please stick to 6.48.4 build. All current commits are work in progress

You can always contact me here: http://forum.xda-developers.com/showthread.php?t=2201860

I will allow you on my PM box if you post there

**Comment by championswimmer** [comment]
A tag at each version state like 6.48.x would be appreciated to help check
that out
(especially to add to the build manifest)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Arnav Gupta (championswimmer)
  Web http://championswimmer.in | Blog http://blog.championswimmer.in |
Twitter http://twitter.com/championswimmer | Facebook
http://facebook.com/championswimmer | Github
http://github.com/championswimmer

**Comment by PhilZ-cwm6** [comment]
what do you mean by a tag?

I wrote here: https://github.com/PhilZ-cwm6/philz_touch_cwm6/commit/c8464932b87a10462592511155358ae2b615eed0

**Comment by JustArchi** [comment]
Modify your roomservice.xml or any manifest that you're using and simply use branch="588dbcf20041d59db7cb32d60c5de6089b02455c". You don't need tag for that.

**Comment by championswimmer** [comment]
Tag is like what aosp has for "android-4.4.4_r1" etc.

What JustArchi said works too, just that tag makes a more human readable
thing instead of an sha hash of commit.

Also what do you mean by CWM dies here, won't work anymore with CWM
upstream?
I am still able to build 6.48.9 perfectly here with cwm inside
bootable/recovery and this recovery in bootable/recovery-philz and using
RECOVERY_VARIANT=philz
It works perfectly without any issues either.

**Comment by PhilZ-cwm6** [comment]
I get it. Didn't think many people outside xda were interested in this. That's why I never bothered to keep a main branch and push work in progress to a different branch

By CWM dies here, I meant that I am breaking with keeping my sources in sync with CWM

Since CWM is now poorly maintained by CM team, I will be porting it for future aosp/CM new recovery compatibility. Let's say, I am no more following CWM, if they want, they can follow me ;-)

Compatibility will be kept for now, no worry

Will clean my repo and push to another branch

When PhilZ Touch 7 is ready in C++, will merge to main stream

**Comment by PhilZ-cwm6** [comment]
Sorry for any trouble:

I reverted main branch and moved all work in progress to cm-11.0-beta branch

**Pull request merged**
