### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tigrouzen**
It is like on 2 first patch added new line but on last you removed them...

Or maybe error on 3 patch ?

### CODE REVIEW

**Comment by sudosurootdev** [comment]
@Tigrouzen You are correct... the other two commits were overwritten by the last one, so there is no need for them anymore. You should also change the line above there, which says: 
`Check these three patches are present in your build/ directory`
to say: 
`Check that this patch is present in your build/ directory`
I haven't seen any commits by @PhilZ-cwm6  in a while though, so I don't know if he'll merge this, at least anytime soon. He forked https://github.com/CyanogenMod/android_bootable_recovery/tree/cm-12.0 a while back but has not made any changes to it... also https://github.com/PhilZ-cwm6/philz_touch_cwm6/tree/cm-11.0 will not build with cm-12.0 ROM builds, because it lacks dependencies which have changed. I thought about beginning to port cm-11.0 to cm-12.0 and pushing here, but I don't know if he is working on it already, or if he is just going to leave it at cm-11.0.

**Comment by Tigrouzen** [comment]
Thank sudosurootdev, anyway we can make mixx, like recovery allready stay cm11 and initramfs cm12 ;)

**Comment by PhilZ-cwm6** [comment]
no need to merge this readme.

Actually, the patches were merged in final cm 11.0, so we can just remove all those lines. A stock repo sync is just fine

I started to work on cm-12.0 SR and stopped quickly. It is a lot of hours work. A simple merge could be fast, but a proper work will need endless hours. Too many bugs and flaws in the GUI and core code.

I no longer have time as I did till now. So for now, it is dropped by me

**Comment by Tigrouzen** [comment]
Thanks Phil.

**Pull request closed without merging**
