### PR TITLE
LGE E610 Support

### PR DESCRIPTION
**Pull request by aidasaidas75**

### CODE REVIEW

**Comment by aidasaidas75** [comment]
there is no official support on xda for l5

**Comment by PhilZ-cwm6** [comment]
I already merged your e610 work
I am just asking why you want to disable NTFS ?

**Comment by aidasaidas75** [comment]
i added it because i want to make commit to add e610 because i cant send you pm on xda

**Comment by aidasaidas75** [comment]
and added other commit https://github.com/aidasaidas75/philz_touch_cwm6/commit/c3c2f4f8c6bc7144fbdf96fb2c4ad2a39050e691

**Pull request closed without merging**
