### PR TITLE
Fix issue #34, #35

### PR DESCRIPTION
**Pull request by arter97**
Hi, it's me again.

After reporting that f2fs formatting issue and your tip, I personally haven't seen any valid git repository that has correctly fixed this issue.

So I've spent some few hours and gone fixing it myself, and found it actually quite easy.

I hope you can merge my pull request to make other f2fs devs life easier :)

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
In fact, this looks ugly bug!

I prefer you to fix it by calling similar code:
__system("mkfs.f2fs [options] [...]");
check if __system call returns 0 else print the strerror(errno) value

If you are unsure how to write it, just send me the exact mkfs.f2fs command line that should work

**Comment by PhilZ-cwm6** [comment]
I am poking @kumajaya for this issue

He did a great work on f2fs support

**Comment by PhilZ-cwm6** [comment]
can you try this:

#ifdef USE_F2FS
    if (strcmp(fs_type, "f2fs") == 0) {
        char cmd[PATH_MAX];
        sprintf(cmd, "mkfs.f2fs %s", device);
        int result = __system(cmd);
        if (result != 0) {
            LOGE("format_volume: mkfs.f2fs failed on %s (%s)\n", device, strerror(errno));
            return -1;
        }
        return 0;
    }
#endif

**Comment by arter97** [comment]
Will test now. Thanks!

ps. format /system as f2fs:
mkfs.f2fs /dev/block/mmcblk0p9

There is a label option "-l SYSTEM" but it seems optional.

**Comment by arter97** [comment]
Tested. Your code works well :)

http://pastebin.com/3akGiHsq

**Comment by arter97** [comment]
Gonna commit it again, and send another pull request :D

**Pull request closed without merging**
