### PR TITLE
Add Sony Xperia M (nicki) support

### PR DESCRIPTION
**Pull request by JustArchi**

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Please push to beta branch. Else it will add a huge mess when I merge beta into master
Else, wait when beta is merged into master and I will merge your commit

**Comment by JustArchi** [comment]
Sure thing!

**Comment by PhilZ-cwm6** [comment]
I will keep it open to merge it later unless you want to push to beta branch

**Comment by JustArchi** [comment]
I pushed to beta :+1:

**Pull request closed without merging**
